### ISSUE TITLE
Panics with "No FTDI device" rather than returning error

### ISSUE THREAD

**Issue by TheDan64** [geomatsi/ftdi-embedded-hal#1]
https://github.com/geomatsi/ftdi-embedded-hal/blob/0eac7743b2cc3c18722bf6634c49fd3ba2f2780d/src/x232h.rs#L58

It would be really useful to be able to loop over a list of devices and try and connect to them. You can't do this though because the first unsuccessful attempt will panic.

**Comment by geomatsi** [comment]
Hi @TheDan64 

Sure, needs to fix it. Besides, support for multiple FTDI devices is also missing. I plan to get back to this project and to rework quite a few things. So I will keep this issue open. But PRs are also welcome if you already came up with some fixes. I don't have enough time to work on development, but I can help with testing.

Regards,
Sergey
