### ISSUE TITLE
not work with ssd1306

### ISSUE THREAD

**Issue by optman** [geomatsi/ftdi-embedded-hal#4]
I have attach a logic analyzer,  the result show that it setup write to 0x78 correctly, but without slave ack. 

I have struggled with this device many days, look like a hardware interface issue. It work with raspberry pi , but not with FT2232H module. 

I would like to know, did anyone ever success with a ssd1306 device?

**Comment by geomatsi** [comment]
Hello @optman 

Could you please be more specific about your issue. So you are trying to communicate with display module SD1306 using FT2232H module. AFAIK that display module supports both I2C and SPI. It looks like you are trying to communicate using I2C protocol. Also you are able to send the first command successfully, but you are not receiving I2C ACK from display module. Correct ?

If so then could you please double-check your hardware circuitry. Do you have proper pull-up resistors for SDA/SCL lines ?

Regards,
Sergey

**Comment by optman** [comment]
@geomatsi  thanks for your quick response

yes, the first write to address 0x78, but without ack received.
![IMG_20200417_120920](https://user-images.githubusercontent.com/2323912/79691283-1ad11400-8291-11ea-979c-effba0f03c5e.jpg)

 
The ssd306 board i have come with internal pull-up 4.7K resistors. I did try it successful on two different SOC boards with linux-embedded-hal package, only fail with ftdi-embedded-hal, that is why i post an issue here.

And i have check and try i2c.rs with different minor changes,  and double check the logic analyzer result with the successful ones.  I am sure the code is right, there is no reason the device not response.

I am sure it is a hardward compatible issue.
